# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/code_projects/mpd/hw5/submit/aquila_ap/aquila_ap.srcs/sources_1/ip/async_fifo_signal/async_fifo_signal.xci
# IP: The module: 'async_fifo_signal' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/code_projects/mpd/hw5/submit/aquila_ap/aquila_ap.gen/sources_1/ip/async_fifo_signal/async_fifo_signal.xdc
# XDC: The top module name and the constraint reference have the same name: 'async_fifo_signal'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/code_projects/mpd/hw5/submit/aquila_ap/aquila_ap.gen/sources_1/ip/async_fifo_signal/async_fifo_signal_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'async_fifo_signal'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/code_projects/mpd/hw5/submit/aquila_ap/aquila_ap.gen/sources_1/ip/async_fifo_signal/async_fifo_signal_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'async_fifo_signal'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/code_projects/mpd/hw5/submit/aquila_ap/aquila_ap.srcs/sources_1/ip/async_fifo_signal/async_fifo_signal.xci
# IP: The module: 'async_fifo_signal' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/code_projects/mpd/hw5/submit/aquila_ap/aquila_ap.gen/sources_1/ip/async_fifo_signal/async_fifo_signal.xdc
# XDC: The top module name and the constraint reference have the same name: 'async_fifo_signal'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/code_projects/mpd/hw5/submit/aquila_ap/aquila_ap.gen/sources_1/ip/async_fifo_signal/async_fifo_signal_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'async_fifo_signal'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/code_projects/mpd/hw5/submit/aquila_ap/aquila_ap.gen/sources_1/ip/async_fifo_signal/async_fifo_signal_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'async_fifo_signal'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
